"""add application document paths

Revision ID: 92a6cab4d15d
Revises: 0776c60f1be9
Create Date: 2026-07-27 09:50:35.488804
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate renders Vector columns as pgvector.sqlalchemy.vector.VECTOR but
# does not emit this import itself.
import pgvector.sqlalchemy


revision: str = '92a6cab4d15d'
down_revision: Union[str, None] = '0776c60f1be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cover_letter_s3_key', sa.String(length=1000), nullable=True))
    op.add_column('applications', sa.Column('cv_local_path', sa.String(length=1000), nullable=True))
    op.add_column('applications', sa.Column('cover_letter_local_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cover_letter_local_path')
    op.drop_column('applications', 'cv_local_path')
    op.drop_column('applications', 'cover_letter_s3_key')
    # ### end Alembic commands ###
